sudo: required
services:
    - docker
    - nodejs
    - phantomjs
before_install:
    - docker-compose up -d
    - cd tests
    - npm install  
script:
    - ./node_modules/casperjs/bin/casperjs tests/casper_test.js
