version: '3'

services:
  mongo:
    image: mongo
    container_name: ca-mongo
  bindaas:
    build: "./Deps/Bindaas/"
    depends_on:
      - "mongo"
    container_name: ca-data
    ports: ["8080:8080", "9099:9099"]
    volumes:
      - ./config/bindaas_projects/:/root/bindaas/bin/projects/
      - ./config/bindaas.config.json:/root/bindaas/bin/bindaas.config.json
  iip:
    build: "https://github.com/camicroscope/iipImage.git"
    container_name: ca-iip
    volumes:
      - ./images/:/images/
  viewer:
    build: "https://github.com/camicroscope/caMicroscope.git#refactor"
    container_name: ca-front
  loader:
    build: "https://github.com/camicroscope/SlideLoader.git"
    container_name: ca-load
    volumes:
      - ./images/:/data/images/
  elevate:
    build: "https://github.com/camicroscope/Security.git#refactor"
    container_name: ca-security
    ports: ["4010:4010"]
    environment:
      - DISABLE_SEC=true
